trigger:
- '*'

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs:
    - job: 'Build'
      displayName: 'Build job'
      pool:
        vmImage: 'Ubuntu-20.04'
        demands:
        - npm

      variables:
        wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
        dotnetSdkVersion: '6.x'

      steps:
        - task: UseDotNet@2
          displayName: '.NET SDKは $(dotnetSdkVersion) を使用'
          inputs:
            version: '$(dotnetSdkVersion)'

        - task: Npm@1
          displayName: "npm installを実行"
          inputs:
            verbose: false

        - script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
          displayName: "Sassアセットをコンパイル"

        - task: gulp@1
          displayName: 'gulpタスクを実行'

        - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
          displayName: 'ビルド情報を記載'
          workingDirectory: $(wwwrootDir)

        - task: DotNetCoreCLI@2
          displayName: 'プロジェクトの依存関係を解決'
          inputs:
            command: 'restore'
            projects: '**/*.csproj'

        - task: DotNetCoreCLI@2
          displayName: 'プロジェクトをビルド - $(buildConfiguration)'
          inputs:
            command: 'build'
            arguments: '--no-restore --configuration $(buildConfiguration)'
            projects: '**/*.csproj'

        - task: DotNetCoreCLI@2
          displayName: 'プロジェクトを公開 - $(buildConfiguration)'
          inputs:
            command: 'publish'
            projects: '**/*.csproj'
            publishWebProjects: false
            arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
            zipAfterPublish: true

        - publish: '$(Build.ArtifactStagingDirectory)'
          artifact: drop
